{% set name = "choppa" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asapdiscovery/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 95bbb8ab0bd684aae7226d3640905ff89e19ecf5d386b692f412778fbbdadb3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - "choppa = choppa.cli.cli:cli"

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >=3.8
    - pandas
    - biopython
    - click
    - mdanalysis
    - click
    - pymol-open-source
    - pyqt
    - prolif
    - logomaker
    - jinja2
    

test:
  imports:
    - choppa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asapdiscovery/choppa
  summary: Integrated mutational and structural biology data into a concerted interactive and portable PyMOL + HTML viewer.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JenkeScheen
    - hmacdope
